### ISSUE TITLE
Undefined: Send.verification.request

### ISSUE THREAD

**Issue by Vasudev-valke** [leggetter/nexmo-rails-2fa-demo#4]
I get below error:
NoMethodError (undefined method `send_verification_request' for #<Nexmo::Client:0x007f5bc039eec8>):
 
app/controllers/application_controller.rb:17:in `start_verification'

**Comment by hummusonrails** [comment]
Hi @Vasudev-valke,

Thank you for raising the issue. I have gone ahead and updated the code in this demo to the most up to date method calls for the Ruby Nexmo client library. You can pull in the latest changes to your local branch and it should be working. 

If you are interested, you can read more about the Nexmo Ruby library at: https://github.com/Nexmo/nexmo-ruby#verify-api.

Have a great day,

Ben
